### ISSUE TITLE
Stack overflow soundness

### ISSUE THREAD

**Issue by tarcieri** [iqlusioninc/usbarmory.rs#11]
It would be nice to have some sound way of handling stack overflow. This is presently an unsolved upstream problem for non-x86/x86_64 platforms:

https://github.com/rust-lang/rust/issues/43241

It seems like the best solution is to implement stack probes for ARM in upstream Rust.

**Comment by japaric** [comment]
We should be able to address this without runtime checks by flipping the layout of the program memory as explained in [this blog post](https://blog.japaric.io/stack-overflow-protection/). Under the hood this requires running the linker twice but from the point of the view of the application author they only have install a linker wrapper and use that linker instead of rustc's lld. We can set the linker wrapper as the default linker in the application template and even make the linking of applications fail if they don't use that specific linker wrapper.

With that in place stack overflows will make one of the exception handlers (`DataAbort` I think) run. That exeception handler should not use the main stack itself or that will result in infinite recursion. Though we can also reserve some small amount of memory for that specific exception handler. In any case, this exception handler should not be fully customizable (that'd be too error prone since it runs in environment with zero or very little memory available for the stack) but instead you should only be able to pick among some sane options like ... reset the SoC, I guess. There aren't too many things you can do if you exhausted the memory dedicated to the stack.
