### ISSUE TITLE
Disabling interrupts for cryptographic operations

### ISSUE THREAD

**Issue by tarcieri** [iqlusioninc/usbarmory.rs#33]
Let me start by saying I'm super excited about RTFM's concurrency support and definitely want to leverage it, and all the work that @japaric has done on interrupt-handling so far has been great.

For an MVP of what we want to deliver with [Armistice](https://github.com/iqlusioninc/armistice), the main unknown with interrupt-driven concurrency and cryptography is potential side-channel leakage in the event an attacker is able to abuse interruptions in a cryptographic algorithm to their advantage somehow.

What I would propose is some sort of "safe point" system where cryptographic algorithms briefly shut off interrupt handling, perform some computation, and then re-enable interrupt handling. See also: "critical sections", etc.

The nice thing about cryptographic algorithms is they literally must run in constant time to be secure, so when you're talking about an algorithm like that and a specific piece of hardware, it should be fairly easy to reason about realtime deadlines.

Complex cryptographic algorithms are pretty much exclusively loops iterating over some number of rounds or otherwise "chunkable" work where it's possible to perform a "step" of a computation, at which point you'd reach a "safe point" and can briefly re-enable and check for interrupts, handle them, and then resume the cryptographic operation in a way which is more or less cooperative and doesn't allow an attacker to influence a cryptographic computation.

I'm imagining some sort of RAII-like API here to obtain a "critical section" where interrupts are disabled, perform some "chunk" of work, and then allow the interrupt handler to run if there are any interrupts to be handled, and once they're all handled enter another "critical section" to perform the next chunk of work.

I'm pretty open in terms of API design though. If RAII works, great. If it needs to take a `Fn*`, that works too.

I think if we really want to keep with the realtime model of RTFM, it'd be nice if (at least in debug mode) it panicked if these "chunks" weren't completed after a specified deadline. In release builds, however, we'd always want to remain available even if we failed to provide hard realtime.

**Comment by japaric** [comment]
There are a few API options to get this no-interrupt behavior.

- Closure API

``` rust
let ret = no_interrupts(|| {
    // run some code
});
```

The closure will run with interrupts disabled. The critical section can,
however, be broken by intentionally or unintentionally re-enabling the
interrupts. Enabling interrupts is generally a `unsafe` operation.

- RAII guard API

``` rust
let cs = disable_interrupts();
// run some code
drop(cs); // re-enables interrupts
```

In general, I'm not a fan of RAII guards because `mem::forget(cs)` or any other
form of memory leakage (e.g. RC cycles) will cause the destructor to not run.
Not running the destructor in this case means the interrupts are never re-enabled.
Leaving the interrupts disabled means RTFM tasks never get to run again.

It's also harder to visualize the critical section with the RAII pattern, IMO.

- no new API; use the highest priority task

``` rust
#[task(priority = 99)]
fn do_crypto(cx: do_crypto::Context) {
    // run some code
}
```

The highest priority task can't be preempted so it effectively runs with
interrupts disabled. Also, there's never context switching from a high priority
task to a lower priority one. 

---

In terms of chunking one could use the closure, or RAII, API from `idle`, the
background task that runs at the lowest priority, to interleave constant-time
code with evented code: 

``` rust
#[idle(resources = [..])]
fn idle(cx: idle::Context) -> ! {
    let channel = cx.resources.channel;
    loop {
        if let Some(data) = channel.recv() {
            let mut res = Default:default();
            for chunk in data.chunks(SOME_SIZE) {
                // tasks cannot run while this work is being performed
                no_interrupts(|| {
                    // constant time work
                    process(chunk, &mut res);
                });
                
                // pending tasks (e.g. USB core logic) will run at this point
            }
            
            cx.spawn.usb_send_response(res);
        } else {
            // no more data; sleep until next message
            sleep();
        }
    }
}
```

One could use the highest priority task instead of `idle` but this requires more
explicit book-keeping.

``` rust
enum State {
    NewData(Data),
    InProgress(Chunks),
}

#[task(spawn = ctw)]
fn some_other_task() {
    // a lower priority task can initiate the CTW task
    let data = /* came from USB, for example */
    cx.spawn.ctw(data);
}

// CTW = Constant-Time-Work
#[task(priority = 99, /* .. */)]
fn ctw(cx: ctw::Context, state: State) {
    // task local data: safe to access
    static mut RESULT: Result = Result::default();

    let result: &mut Result = RESULT;
    let (chunk, left) = match state {
        State::NewData(data) => {
            let mut chunks = data.chunks(SOME_SIZE);
            (chunks.next(), chunks)
        }
        
        State::InProgress(chunks) => {
            (chunks.next(), chunks)
        }
    };
    
    process(chunk, result);
    
    if chunks.is_empty() {
        // done
        cx.spawn.usb_send_response(result.clone());
        result = Default::default();
    } else {
        // not done
        // re-run this task in 150 microseconds; during those 150 microseconds
        // other tasks (like the USB core logic) can run
        cx.schedule.ctw(State::InProgress(chunks), Duration::from_micros(200))
    }
}
```

---

In terms of keeping an eye on the time spent in the critical section mode we can
add a `debug_timeout` API that looks like this:

``` rust
let timeout = core::time::Duration::from_micros(125); // 1 USB micro-frame
let ret = debug_timeout(timeout, || {
    // do some work
});
```

And that will panic, when debug assertions are enabled, if the work is not
completed within the `timeout`. This API can be used with either the `idle` or
highest priority task patterns shown above.

**Comment by japaric** [comment]
To start with I have added the `no_interrupts` and `debug_timeout` APIs in #34. I can add a complete RTFM example of chunked work in `idle` if so desired.

**Comment by tarcieri** [comment]
> I can add a complete RTFM example of chunked work in idle if so desired.

That'd be great. Otherwise I'm going to go ahead and close this as `no_interrupts` and `debug_timeout` look like they do the trick.
